owner: thewilloftheshadow
repo: utopium-status

sites:
  - name: Werewolf Utopium
    url: https://werewolf-utopium.tk
  - name: Spyfall Utopium
    url: https://spyfall.utopium.tk

status-website:
  cname: status.utopium.tk
  logoUrl: https://cdn.discordapp.com/emojis/681383341840400463.png?v=1
  name: Utopium Status
  introTitle: "Status Page for **Werewolf Utopium**"
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://werewolf-utopium.tk
    - title: Server
      href: https://werewolf-utopium.tk/invite

assignees:
  - thewilloftheshadow
  
notifications:
  - type: discord
